title    NovaOS Live (x86_64)
sort-key 01
linux    /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux
initrd   /%INSTALL_DIR%/boot/intel-ucode.img,/%INSTALL_DIR%/boot/amd-ucode.img,/%INSTALL_DIR%/boot/x86_64/initramfs-linux.img
options  archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% novaos.boot=live nouveau.modeset=1 radeon.cik_support=0 radeon.si_support=0 amdgpu.si_support=1 amdgpu.cik_support=1 i915.fastboot=1 i915.enable_fbc=1 i915.enable_guc=2 quiet splash loglevel=3 systemd.show_status=false
